'use client'

import Link from 'next/link'
import { ArrowLeft, Check, ChevronRight, Lightbulb, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Bud, Header } from '@/components/illume-dashboard'

type TopicKey = 'Math' | 'Science' | 'Reading'
type FollowUp = { question: string; placeholder: string; response: string }
type Spot = { id: number; name: string; why: string; lit: boolean }
type TopicConfig = { followUps: FollowUp[]; concepts: Spot[]; prompt: string }

const TOPICS: Record<TopicKey, TopicConfig> = {
  Math: { followUps: [{ question: 'How would you explain adding two fractions with different denominators to a friend?', placeholder: 'I think you start by...', response: 'You are noticing that fractions are pieces of a whole.' }, { question: 'Why do we need a common denominator before adding fractions?', placeholder: 'We need the same denominator because...', response: 'Exactly. A common denominator makes every piece the same size, so the pieces can be combined fairly.' }, { question: 'How would you simplify 6/8, and why does the value stay the same?', placeholder: 'I can divide the numerator and denominator by...', response: 'Great thinking. Dividing both parts by the same factor renames the same amount with simpler numbers.' }], concepts: [{ id: 1, name: 'Equivalent fractions', why: 'You can compare pieces, but the connection between numerator and denominator is still forming.', lit: false }, { id: 2, name: 'Common denominators', why: 'You started the right way, then mixed the sizes of the pieces.', lit: false }, { id: 3, name: 'Simplifying', why: 'Your final answer is correct, but the last step can be made clearer.', lit: true }], prompt: 'Each question checks the idea underneath the last one.' },
  Science: { followUps: [{ question: 'How would you explain why water changes from a liquid into a gas?', placeholder: 'When water gets warmer...', response: 'You connected heat to movement. Water particles gain energy and begin moving faster.' }, { question: 'What happens to water particles as they gain more heat?', placeholder: 'The particles start to...', response: 'Yes. Faster particles spread farther apart, which explains the difference between liquid and gas.' }, { question: 'What is evaporation, and where does it happen?', placeholder: 'Evaporation happens when...', response: 'Well done. Evaporation is when energetic particles at a liquid’s surface escape into the air.' }], concepts: [{ id: 1, name: 'Particle energy', why: 'You noticed heat matters, but the invisible particle movement is still forming.', lit: false }, { id: 2, name: 'States of matter', why: 'The difference between a liquid and a gas could be sharper.', lit: false }, { id: 3, name: 'Evaporation', why: 'You have the big idea and can now connect it to the process name.', lit: true }], prompt: 'Keep connecting what you can see to what the particles are doing.' },
  Reading: { followUps: [{ question: 'How would you explain the main idea of a story to a friend?', placeholder: 'The story is mostly about...', response: 'You are looking for the story’s big message and connecting repeated details.' }, { question: 'Which details help you decide what the main idea is?', placeholder: 'The important details are...', response: 'That is the right move. Key details support the bigger message, while interesting details may not.' }, { question: 'How is a theme different from a main idea?', placeholder: 'A theme is..., while the main idea...', response: 'Excellent. The main idea is what a text is mostly about; theme is the lasting message.' }], concepts: [{ id: 1, name: 'Key details', why: 'You found an interesting detail, but not every detail carries equal weight.', lit: false }, { id: 2, name: 'Theme', why: 'The lesson of the story is close, but needs a little more evidence.', lit: true }, { id: 3, name: 'Main idea', why: 'You can summarize what happened and are ready to name what matters most.', lit: false }], prompt: 'Keep looking for evidence that connects the big idea to details.' },
}

export default function Diagnose() {
  const [stage, setStage] = useState<'form' | 'loading' | 'results' | 'celebrate'>('form')
  const [topic, setTopic] = useState<TopicKey>('Math')
  const [questionIndex, setQuestionIndex] = useState(0)
  const [answer, setAnswer] = useState('')
  const [spots, setSpots] = useState(TOPICS.Math.concepts)
  const config = TOPICS[topic]
  const question = config.followUps[questionIndex]

  function changeTopic(value: TopicKey) { setTopic(value); setQuestionIndex(0); setAnswer(''); setSpots(TOPICS[value].concepts); setStage('form') }
  async function submit() { setStage('loading'); await fetch('/api/illume', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic, answer, questionIndex }) }); setTimeout(() => setStage('results'), 700) }
  function continueToFollowUp() { const next = questionIndex + 1; setSpots((current) => current.map((spot, index) => index === questionIndex ? { ...spot, lit: true } : spot)); setAnswer(''); if (next >= config.followUps.length) setStage('celebrate'); else { setQuestionIndex(next); setStage('form') } }

  return <div className="light-flow"><Header /><div className="container-shell py-10 md:py-16">
    {stage === 'form' && <div className="mx-auto max-w-2xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted"><ArrowLeft size={16} /> Dashboard</Link><div className="mt-10"><p className="text-sm font-semibold uppercase tracking-[.2em] text-indigo">Diagnostic {String(questionIndex + 1).padStart(2, '0')} of 03</p><h1 className="font-heading mt-3 text-5xl leading-tight">Show me how you think.</h1><p className="mt-4 text-lg leading-8 text-muted">We&apos;ll keep asking gentle follow-ups on the same topic until the fundamentals are clear.</p></div><div className="mt-10 space-y-6"><label className="block"><span className="text-sm font-semibold">Topic</span><select value={topic} onChange={(event) => changeTopic(event.target.value as TopicKey)} className="focus-ring mt-2 w-full rounded-2xl border border-indigo/20 bg-white p-4 text-ink"><option>Math</option><option>Science</option><option>Reading</option></select></label><div className="rounded-3xl bg-indigo p-6 text-white"><p className="text-sm text-white/70">Follow-up question</p><p className="font-heading mt-3 text-2xl">{question.question}</p></div><label className="block"><span className="text-sm font-semibold">Your explanation</span><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder={question.placeholder} className="focus-ring mt-2 min-h-40 w-full resize-y rounded-2xl border border-indigo/20 bg-white p-4 text-ink" /></label><button onClick={submit} disabled={!answer.trim()} className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-50">Check my understanding <ChevronRight size={18} /></button></div></div>}
    {stage === 'loading' && <div className="mx-auto flex max-w-xl flex-col items-center py-20 text-center"><Bud mood="thinking" /><h2 className="font-heading mt-8 text-4xl">Bud is listening closely...</h2><p className="mt-3 text-muted">Checking your answer before choosing the next question.</p></div>}
    {stage === 'results' && <div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-indigo">{topic} follow-up {questionIndex + 1}</p><h1 className="font-heading mt-3 text-5xl">Aha, let&apos;s build on that.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted">{question.response}</p></div><Bud mood="happy" /></div><div className="mt-10 grid gap-4 md:grid-cols-3">{spots.map((spot, index) => <div key={spot.id} className={`${spot.lit || index === questionIndex ? 'glow-card' : 'dim-card'} text-left`}><div className="flex items-center justify-between"><span className="text-sm font-semibold">{spot.lit || index === questionIndex ? 'Lit up' : 'Ready to explore'}</span>{spot.lit || index === questionIndex ? <Check size={18} /> : <Lightbulb size={18} />}</div><h3 className="font-heading mt-8 text-2xl">{spot.name}</h3><p className="mt-2 text-sm leading-6 opacity-75">{spot.why}</p></div>)}</div><button onClick={continueToFollowUp} className="button-primary mt-8 w-full md:w-auto">{questionIndex + 1 >= config.followUps.length ? 'Finish diagnostic' : 'Continue to the next question'} <ChevronRight size={18} /></button><div className="mt-8 rounded-3xl bg-navy p-6 text-white"><p className="text-sm text-white/70">Bud&apos;s approach</p><p className="mt-2 text-lg">{config.prompt}</p></div></div>}
    {stage === 'celebrate' && <div className="mx-auto flex max-w-xl flex-col items-center py-16 text-center"><Bud mood="celebrating" size="lg" /><p className="mt-8 text-sm font-semibold uppercase tracking-[.2em] text-indigo">Fundamentals clear</p><h1 className="font-heading mt-3 text-5xl">Your constellation is glowing.</h1><p className="mt-4 text-lg leading-8 text-muted">You worked through {config.followUps.length} connected {topic.toLowerCase()} questions. That steady thinking is what makes learning stick.</p><Link href="/" className="button-primary mt-8">Back to dashboard <Sparkles size={16} /></Link></div>}
  </div></div>
}
